[kafka]
kafka-topic = "integration"
kafka-brokers = "127.0.0.1:8410"
kafka-group = "metric-transfer"
thread-num = 4

[log]
log-path = "/Users/nongcaihua/go/src/metric-transfer/"
log-level = "info"

[network-filter]
network-filter-enable = true
network-metrics = [{"metric": "cpu.idle", "dimensions": [{"k": "name", "v": "abc"}]}, {"metric": "disk.io.write.bytes/s", "dimensions": [{"k": "name", "v": "cds-s3-proxy"}]}]

[http-sender]
http-sender-enable = true
http-sender-api = "http://127.0.0.1:1890/push"
#sender interval : unit Second
http-sender-interval = 10